baseURL = 'https://blog.octopus-labs.xyz'
languageCode = 'en-us'
title = 'Octopus Labs official blog'

enableEmoji = true

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"


[[params.socialIcons]]
name = "github"
url = "https://github.com/octopuslabs-xyz"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"